[IG]
ig = fsh-generated/resources/ImplementationGuide-smart.who.int.ccc.json

# Correct way to use the local WHO template you downloaded
template =  who.template.root#current
usage-stats-opt-out = false
