[IG]
ig = fsh-generated/resources/ImplementationGuide-smart.who.int.ccc.json
# who.template.root#current dowload from smart-base
template = template = /home/publisher/local-template

usage-stats-opt-out = false
fhirVersion = 4.0.1
extension = .json