id: smart.who.int.ccc
canonical: https://smart.who.int/ccc
name: Ccc
title: "WHO FHIR Implementation Guide (IG): Integrated Management of Childhood Illness (IMCI) in emergencies"
description: This implementation guide provides implementation resources and guidance in support of applying the WHO recommendations on emergency care.<br/>This implementation guide is part of the WHO Smart Guidelines approach to support countries to integrate WHO global data and health recommendations into digital systems accurately and consistently.
version: 0.1.0
status: draft
experimental: false
date: 2022-01-06
publisher:
  name: World Health Organization (WHO)
  url: https://www.who.int
contact:
  - telecom:
    - system: url
      value: https://www.who.int
jurisdiction:
  - coding:
    - system: http://unstats.un.org/unsd/methods/m49/m49.htm
      code: "001"
packageId: smart.who.int.ccc
license: CC0-1.0
fhirVersion: 4.0.1

# ====================== Dependencies ======================
dependencies:
  hl7.fhir.uv.cpg: 1.0.0
  hl7.fhir.us.cqfmeasures: current

# ====================== Pages ======================
pages:
  toc.html:
    title: Table of Contents
    generation: html
    index.md:
      title: Home
      generation: markdown
    documentation.md:
      title: Documentation
      generation: markdown
    guidance.md:
      title: Guidance
      generation: markdown
    downloads.html:
      title: Downloads
      generation: html
    license.md:
      title: License
      generation: markdown
    changes.html:
      title: Changes
      generation: html
    quick-start.html:
      title: Quick Start
      generation: html

# ====================== Parameters ======================
parameters:
  copyrightyear: 2022+
  releaselabel: CI Build
  find-other-resources: true

  path-pages:
    - ext-ig/cpg
    - ext-ig/who
    - input/pagecontent

  path-resource:
    - input/resources/activitydefinition
    - input/resources/library
    - input/resources/plandefinition
    - input/profiles/
    - input/extensions/
    - input/resources/questionnaire
    - input/resources/structuremap
    - input/vocabulary/codesystem
    - input/vocabulary/valueset

  path-liquid: templates/liquid
  path-suppressed-warnings: input/ignoreWarnings.txt
  excludettl: true

  special-url:
    - http://fhir.org/guides/who/core/StructureDefinition/who-doNotPerformReason
    - http://fhir.org/guides/who/core/StructureDefinition/who-notDone
    - http://fhir.org/guides/who/core/StructureDefinition/who-notDoneReason
    - http://fhir.org/guides/who/core/StructureDefinition/who-reportedLocation
    - http://fhir.org/guides/who/core/StructureDefinition/who-allergyintolerance
    - http://fhir.org/guides/who/core/StructureDefinition/who-appointment
    - http://fhir.org/guides/who/core/StructureDefinition/who-careplan
    - http://fhir.org/guides/who/core/StructureDefinition/who-careteam
    - http://fhir.org/guides/who/core/StructureDefinition/who-condition
    - http://fhir.org/guides/who/core/StructureDefinition/who-encounter
    - http://fhir.org/guides/who/core/StructureDefinition/who-episodeofcare
    - http://fhir.org/guides/who/core/StructureDefinition/who-group
    - http://fhir.org/guides/who/core/StructureDefinition/who-groupdefinition
    - http://fhir.org/guides/who/core/StructureDefinition/who-immunization
    - http://fhir.org/guides/who/core/StructureDefinition/who-immunizationnotdone
    - http://fhir.org/guides/who/core/StructureDefinition/who-location
    - http://fhir.org/guides/who/core/StructureDefinition/who-measurereport
    - http://fhir.org/guides/who/core/StructureDefinition/who-medicationnotrequested
    - http://fhir.org/guides/who/core/StructureDefinition/who-medicationrequest
    - http://fhir.org/guides/who/core/StructureDefinition/who-observation
    - http://fhir.org/guides/who/core/StructureDefinition/who-observationnotdone
    - http://fhir.org/guides/who/core/StructureDefinition/who-organization
    - http://fhir.org/guides/who/core/StructureDefinition/who-patient
    - http://fhir.org/guides/who/core/StructureDefinition/who-practitioner
    - http://fhir.org/guides/who/core/StructureDefinition/who-practitionerrole
    - http://fhir.org/guides/who/core/StructureDefinition/who-procedure
    - http://fhir.org/guides/who/core/StructureDefinition/who-procedurenotdone
    - http://fhir.org/guides/who/core/StructureDefinition/who-relatedperson
    - http://fhir.org/guides/who/core/StructureDefinition/who-servicenotrequested
    - http://fhir.org/guides/who/core/StructureDefinition/who-servicerequest

# ====================== MENU ======================
menu:
  Home:
    Summary: index.html
    Changes: changes.html
    Quick Start: quick-start.html
    Documentation: documentation.html
    Guidance: guidance.html
    Downloads: downloads.html
    License: license.html

  Business Requirements:
    Concepts: concepts.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Indicators: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html

  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html

  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html